#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('./lib', __FILE__)
require './lib/codebreaker/game'

game = Codebreaker::Game.new(STDOUT,'simple_board.txt')
# binding.pry
game.start('simple_moves.txt')

