#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('./lib', __FILE__)
require './lib/codebreaker/game'

game = Codebreaker::Game.new(STDOUT)
# binding.pry
game.black_or_white('a2','simple_board.txt')

