#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('./lib', __FILE__)
require './lib/robots'

config[:add_boxing_charge] = true
ship = ShippingQuote::Shipping.new(cart_items, config)
packages = ship.create_packages
#boxing = ship.boxing_charge
quote = ship.quotes(destination,packages)
results = ship.filter_shipping(quote, destination)
puts results
#has_express = quote.select{|key, value| key.to_s.match(/^FedEx Express Saver/)}




#quotes = ship.quotes(destination,packages)
#truck_only = ship.truck_only
#puts truck_only
#packages = ship.create_packages
#quotes = ship.quotes(destination,packages)
#puts results = ship.filter_shipping(quotes, nil, nil, truck_only)
